server:
  port: 9001
  servlet:
    context-path: /department-service
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deaprtmet_service?useSSL=false
    username: root
    password: Ati@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
   
    hibernate:
      ddl-auto: update
    show-sql: true
      
  application:
    name: department-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
